# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."teamspeak-server" = {
    image = "teamspeaksystems/teamspeak6-server:latest";
    environment = {
      "TSSERVER_LICENSE_ACCEPTED" = "accept";
    };
    volumes = [
      "/var/lib/teamspeak-data:/var/tsserver:rw"
    ];
    ports = [
      "9987:9987/udp"
      "30033:30033/tcp"
      "10080:10080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=teamspeak"
      "--network=teamspeak6_default"
    ];
  };
  systemd.services."docker-teamspeak-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-teamspeak6_default.service"
    ];
    requires = [
      "docker-network-teamspeak6_default.service"
    ];
    partOf = [
      "docker-compose-teamspeak6-root.target"
    ];
    wantedBy = [
      "docker-compose-teamspeak6-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-teamspeak6_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f teamspeak6_default";
    };
    script = ''
      docker network inspect teamspeak6_default || docker network create teamspeak6_default
    '';
    partOf = [ "docker-compose-teamspeak6-root.target" ];
    wantedBy = [ "docker-compose-teamspeak6-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-teamspeak6-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };

  networking.firewall.allowedUDPPorts = [ 9987 ];
  networking.firewall.allowedTCPPorts = [ 30033 10080 ];
}
