{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."homarr" = {
    image = "ghcr.io/homarr-labs/homarr:latest";
    environment = {
      "SECRET_ENCRYPTION_KEY" = "c59e1cf13ce4c9926b83923ae5967b9d4b38399a87a463fcaca888419f10bc7e";
      "AUTH_PROVIDERS" = "credentials,oidc";
      "AUTH_OIDC_ISSUER" = "https://auth.kaiwelsh.me";
      "AUTH_OIDC_CLIENT_ID" = "homarr";
      "AUTH_OIDC_CLIENT_SECRET" = "itsNotesT1m3!";
      "AUTH_OIDC_CLIENT_NAME" = "Authelia";
      "AUTH_OIDC_FORCE_USERINFO" = "true";
      "AUTH_OIDC_SCOPE_OVERWRITE" = "openid profile email groups";
      "NEXTAUTH_URL" = "https://home.kaiwelsh.me";
      "AUTH_TRUST_HOST" = "true";
    };
    volumes = [
      "/home/sysop/nix-config/modules/homarr/homarr/appdata:/appdata:rw"
      "/var/run/docker.sock:/var/run/docker.sock:rw"
    ];
    ports = [
      "7575:7575/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=homarr"
      "--network=homarr_default"
    ];
  };
  systemd.services."docker-homarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-homarr_default.service"
    ];
    requires = [
      "docker-network-homarr_default.service"
    ];
    partOf = [
      "docker-compose-homarr-root.target"
    ];
    wantedBy = [
      "docker-compose-homarr-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-homarr_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f homarr_default";
    };
    script = ''
      docker network inspect homarr_default || docker network create homarr_default
    '';
    partOf = [ "docker-compose-homarr-root.target" ];
    wantedBy = [ "docker-compose-homarr-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-homarr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
